font_family JetBrainsMono Nerd Font
font_size 17.0

disable_ligatures no
enable_audio_bell no

shell             zsh
shell_integration disabled

cursor_shape beam

url_style curly


map ctrl+shift+c    copy_to_clipboard
map ctrl+v          paste_from_clipboard
map ctrl+shift+v    paste_from_clipboard
map home            send_text all \x1b[H
map end             send_text all \x1b[F

remember_window_size  no
initial_window_width  640
initial_window_height 480
window_padding_width  20
cursor_blink_interval 0

background_opacity         0.35
scrollbar_handle_opacity   0
scrollbar_track_opacity    0
scroll_track_hover_opacity 0
confirm_os_window_close    0

sync_to_monitor no

# Основные цвета
background            #282a36
foreground            #f8f8f2
cursor                #bbbbbb
selection_background  #44475a
selection_foreground  #1e1f28

# Цветовая палитра

# Black (вместо черного — мягкий серый, как просила)
color0  #3b3d4d
color8  #949494

# Red (приглушенный)
color1  #e35e5e
color9  #ff5454

# Green (пастельный)
color2  #70da8e
color10 #50fa7b

# Yellow (песочный)
color3  #e6db74
color11 #f0fa8b

# Blue (спокойный)
color4  #9a86e0
color12 #bd92f8

# Magenta 
color5  #ff78c5
color13 #ff78c5

# Cyan (мягкий морской)
color6  #7bc6d4
color14 #8ae9fc

# White
color7  #bbbbbb
color15 #ffffff
