# --- ОСНОВНЫЕ НАСТРОЙКИ ---
allow_empty_password = true
animation = none
animation_timeout_sec = 0
asterisk = *
auth_fails = 10
battery_id = null

# --- ЦВЕТА (ВЗЯТО ИЗ ТВОЕГО KITTY) ---
# Нежно-розовый #ff78c5
fg = 0x00FF78C5
border_fg = 0x00FF78C5
bg = 0x00000000
full_color = true

# --- ОГРОМНЫЕ ЧАСЫ (BIGCLOCK) ---
# Включаем их обратно!
bigclock = en
bigclock_12hr = false
bigclock_seconds = false

# Маленькие часы в углу отключаем, чтобы не мешались
clock = null

# --- ВИЗУАЛ ---
blank_box = true
hide_borders = false
hide_key_hints = false
hide_keyboard_locks = false
# Версию скрываем, как ты и просила
hide_version_string = true
box_title = null
text_in_center = false

# --- КНОПКИ УПРАВЛЕНИЯ (БЕЗ ЯРКОСТИ) ---
shutdown_cmd = /sbin/shutdown -h now
shutdown_key = F1
restart_cmd = /sbin/shutdown -r now
restart_key = F2
# Яркость полностью убрана
brightness_down_cmd = null
brightness_down_key = null
brightness_up_cmd = null
brightness_up_key = null

# --- ОСТАЛЬНОЕ ---
auto_login_service = ly-autologin
auto_login_session = null
auto_login_user = null
default_input = login
input_len = 34
lang = en
margin_box_h = 2
margin_box_v = 1
numlock = false
save = true
service_name = ly
vi_mode = false

# Пути к сессиям
waylandsessions = /usr/share/wayland-sessions
xsessions = /usr/share/xsessions
xinitrc = ~/.xinitrc
